### ISSUE TITLE
Crash when mining with the Diamond Hammer. (Maybe all tools?)

### ISSUE THREAD

**Issue by Gbergz** [ldtteam/vanilla-tools#1]
Title^

Crashing as soon as i try to mine with the Diamond Hammer, might be with all tools. Also couldn't break any blocks with it in Creative mode.

Crash report: https://hastebin.com/afuticoyoq

**Comment by Raycoms** [comment]
Can you check out the newest version on curse and test if it works?

Am Mo., 18. Feb. 2019 um 09:28 Uhr schrieb Gbergz <notifications@github.com

**Comment by Gbergz** [comment]
Yes now it works! Thanks :) 

But now that i'm speaking to you i might aswell tell you that every Item has the Durability of "59" even the diamond tools. + The "en_us.lang" doesn't seem to exist since the names for items are: "item.supertools.hammerdiamond" etc. (Language files)

Anyways thanks for creating this mod :D

**Comment by Raycoms** [comment]
Fixed the language strings, the durability is on purpose like that, you have the same durability as the pickaxes and normal shovels but it only decreases once per mining operation and not once per block.
