### ISSUE TITLE
1.12.2 - Hammer Ignores Harvest Level

### ISSUE THREAD

**Issue by DonTheBreton** [ldtteam/vanilla-tools#11]
Using a hammer, one may mine a block breakable with stone, and acquire adjacent blocks of higher mining levels. For example, mining stone beside a gold ore with a stone hammer, acquires the gold ore.

Using a shovel on an easily broken block such as tall grass digs adjacent blocks instantly.

Version: 1.2

**Comment by ravenbuilder934** [comment]
Does this still happen on 1.16?

**Comment by ravenbuilder934** [comment]
I did some testing, and I can't reproduce either of these. In both cases, the tool only breaks the middle block (the stone/tall grass).
