### ISSUE TITLE
1.14.4 - Hammer Ignores Mining Level (2 ways)

### ISSUE THREAD

**Issue by RepoDraghon** [ldtteam/vanilla-tools#12]
1st. Ignores mining level if mining like a stone level tool on a stone next to ore of a diamond level.
2nd. I've noticed that the Iron Hammer ignores Redstone that should easily be mined by an Iron Axe.
I am unsure about Diamond Hammers at this point but will update...

**Comment by ravenbuilder934** [comment]
Does this still happen on 1.16?

**Comment by ravenbuilder934** [comment]
1 is a duplicate of #11 
I can't reproduce 2, my iron hammer mined redstone ore and redstone blocks perfectly fine
