### ISSUE TITLE
Minecraft 1.15.2 Mystical Agriculture blocks not affected

### ISSUE THREAD

**Issue by RepoDraghon** [ldtteam/vanilla-tools#15]
I thought it was specifically the ores but it looks like other blocks from the mod too...

**Comment by Raycoms** [comment]
I suppose the mod doesn't implement the according files

**Comment by RepoDraghon** [comment]
That maybe but Vanilla Hammers by MelanX works fine so it's not Mystical Agriculture's issue

**Comment by Raycoms** [comment]
Yeah, I used the hackier way that wrks with all blcks in 1.16 already.

**Comment by ravenbuilder934** [comment]
I can't reproduce this. Hammers break Mystical Agriculture blocks perfectly fine in my test world.
