### ISSUE TITLE
1.16.1 insta mine and no durability loss!

### ISSUE THREAD

**Issue by hiimwolf** [ldtteam/vanilla-tools#16]
its all in the video 

https://youtu.be/bhtY3ukY_es

**Comment by Raycoms** [comment]
Ty, Ill check it out on the weekend

**Comment by hiimwolf** [comment]
do you guys mind if i keep the video public or should i private it?

**Comment by Raycoms** [comment]
I don't mind

**Comment by Raycoms** [comment]
Fixed, uploading now
