### ISSUE TITLE
Tools doesn't have any recipes.

### ISSUE THREAD

**Issue by Gbergz** [ldtteam/vanilla-tools#2]
Is this intended? :)

**Comment by Raycoms** [comment]
They should be 9 shovels, or 9 pickaxes, isn't this working? Only 1.12.2?
1.13.2?

Am Fr., 22. Feb. 2019 um 10:27 Uhr schrieb Gbergz <notifications@github.com

**Comment by Gbergz** [comment]
I'm on 1.13.2 sorry forgot to mention that.

No tools have recipes.

**Comment by Raycoms** [comment]
I'll check into it

Am Fr., 22. Feb. 2019 um 10:52 Uhr schrieb Gbergz <notifications@github.com

**Comment by Raycoms** [comment]
Fixed and uploaded
