### ISSUE TITLE
[Crash] Crash when destroying blocks

### ISSUE THREAD

**Issue by KrolMC** [ldtteam/vanilla-tools#23]
Hello,
When I destroying block using Stone Hammer game crashes ;c

Minecraft: 1.17.1
Vanilla Tools Version: 1.0
Crash Log: [crash-2021-07-25_13.22.11-client.txt](https://github.com/ldtteam/vanilla-tools/files/6873777/crash-2021-07-25_13.22.11-client.txt)

EDIT: When I again loaded a game i didn't break any blocks using hammer.

**Comment by Raycoms** [comment]
Fix uploaded
