### ISSUE TITLE
Current version states it works with 1.20.1 but it only works with 1.20

### ISSUE THREAD

**Issue by Vezta6831** [ldtteam/vanilla-tools#38]
I put this on my server and in my mods, and when I try to join the server it shows an incompatibility. It says I need version 1.20 of minecraft to play on it due to the Vanilla plus Tools mod

**Comment by Talyda** [comment]
It works fine with 1.20.1 - am using it at the moment!  vanillaplustools-1.20-1.0.jar in 1.20.1

**Comment by Vezta6831** [comment]
That is the one I downloaded, strange

**Comment by Raycoms** [comment]
We also use it on a 1.20.1 server and it works just fine for us. Can you show us your log when this happens?

**Comment by Vezta6831** [comment]
I reinstalled the mod locally and on the server and it works like normal now. I am not sure what happened
