### ISSUE TITLE
1.0.2 / NeoForge 21.1.61 Unable to Craft Tools

### ISSUE THREAD

**Issue by wendall911** [ldtteam/vanilla-tools#44]
I saw that the ability to add enchantments was added! So cool. However, the tools are now not craftable. The latest code has not been pushed up for 1.21.1 so I can't inspect to see what broke this.

**Comment by Raycoms** [comment]
Fixed, wasn't working before either =D wonder why no one noticed this =P

**Comment by wendall911** [comment]
Oh, I would have noticed, but I made like three hammers and have been using them for weeks now! Thanks for fixing.
