### ISSUE TITLE
Client will not even load cannot even generate a crash report minecraft 1.14.4

### ISSUE THREAD

**Issue by raziel23x** [ldtteam/vanilla-tools#5]
Like the title says cannot even get the client to load it just crashes and cannot even generate a crash report

if i disabled this mod the client loads just fine

Vanilla+ Tools-1.14.4-2.0
Minecraft 1.14.4
forge-1.14.4-28.0.20

**Comment by Raycoms** [comment]
did it work now?

Am So., 28. Juli 2019 um 17:17 Uhr schrieb Raziel23x <
notifications@github.com>:

**Comment by raziel23x** [comment]
i double posted  by mistake because i did nto see the issue post the first time

**Comment by raziel23x** [comment]
https://github.com/ldtteam/vanilla-tools/issues/4 my original post that did not show up the first time for some reason

**Comment by Raycoms** [comment]
I'll check it out in a bit.

Am So., 28. Juli 2019 um 17:27 Uhr schrieb Raziel23x <
notifications@github.com>:

**Comment by Nightenom** [comment]
@Raycoms wrong bus on one of those
Mod.EventBusSubscriber.Bus.MOD.bus().get().register(LifecycleSubscriber.class);
Mod.EventBusSubscriber.Bus.MOD.bus().get().register(WorldEvents.class);
edit: the second one should be FORGE

**Comment by Raycoms** [comment]
Uploaded fix
