### ISSUE TITLE
3x3 Mining not working in 1.14.4 on Forge 28.0.9

### ISSUE THREAD

**Issue by jon-bartus** [ldtteam/vanilla-tools#8]
On 1.14.4 running Forge 28.0.9 (Have not tested with other versions) this mod seems to be broken. I am playing survival so I'm hesitant to throw any more resources at it (brand new world, starting from scratch) but at least with regards to the stone hammer it's just mining 1x1. Another user has noted the same with a diamond hammer.

**Comment by Raycoms** [comment]
Please update to a newer forge version

**Comment by jon-bartus** [comment]
Ugh, my apologies, Twitch has them ordered stupidly and I just picked the one at the top of the list (which appeared to be descending) thinking it was the newest. Guess they were expecting leading zeroes or something when they programmed their sorting. I'll give that a try tonight

**Comment by jon-bartus** [comment]
So unfortunately that doesn't seem to have done it. Happy to be running the latest Forge of course, but still rocking 1x1 mining on 28.0.45

Edit: Or not... it seems to be hit or miss. Do the tools have a chance of not succeeding?

Edit 2: Okay so I think I know what's going on now. It seems it doesn't like water. If the blocks are underwater it just does 1x1.

**Comment by Raycoms** [comment]
That's weird, it works for me locally

Am Mi., 7. Aug. 2019 um 22:27 Uhr schrieb Jon Bartus <
notifications@github.com>:

**Comment by jon-bartus** [comment]
I think you must have missed my edits. Seems to work okay unless the dirt is behind water.

**Comment by Raycoms** [comment]
yeah, gmail doesn't show those.
Within the water, I can test this

**Comment by jon-bartus** [comment]
Gotta love those edge cases. Would you prefer that I close this and open a new issue with a relevant subject and without the extra details?

**Comment by Raycoms** [comment]
That'd be nice

Am Mi., 7. Aug. 2019 um 23:02 Uhr schrieb Jon Bartus <
notifications@github.com>:
