### ISSUE TITLE
3x3 Digging (May or may not affect other tools) does not work when target is in the water.

### ISSUE THREAD

**Issue by jon-bartus** [ldtteam/vanilla-tools#9]
The subject line pretty much says it all but, for thoroughness' sake, I'll restate it here.

When attempting to do some underwater excavating I discovered that the shovel only digs 1x1 when the blocks it is targeting are under water. This is true both when they are deeply submerged as well as when at a depth of 1 block and mined while standing. Standing in the water or on adjacent blocks does not seem to make a difference.

Steps to reproduce:
1) Craft a Wooden Shovel (Mod version, 9x Vanilla Shovels to craft)
2) Attempt to clear dirt which is located under the water.

**Comment by Raycoms** [comment]
Fix pushed, sorry for the delay, was porting our other mods =D
